# Use the official NGINX base image
FROM nginx:latest
ENV TZ="America/Sao_Paulo"
COPY ./docker/nginx/certs /etc/nginx/certs
COPY ./docker/nginx/website/default.conf /etc/nginx/templates/default-template.conf
COPY ./docker/nginx/website/nginx.conf /etc/nginx/nginx.conf
RUN echo "" > /etc/nginx/cloudflare
RUN curl -s -L https://www.cloudflare.com/ips-v4 | awk '{print "set_real_ip_from " $1";"}' >> /etc/nginx/cloudflare
RUN curl -s -L https://www.cloudflare.com/ips-v6 | awk '{print "set_real_ip_from " $1";"}' >> /etc/nginx/cloudflare
RUN echo "real_ip_header CF-Connecting-IP;" >> /etc/nginx/cloudflare
CMD envsubst '\$DOMAIN_NAME' < /etc/nginx/templates/default-template.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'